services:
  angular-prod:
    build:
      context: .
      target: production
    ports:
      - 8080:80
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.familydashboard-frontend-n3lbeh-2-web.rule=Host(`frontend.erikbreuer.de`)
      - traefik.http.routers.familydashboard-frontend-n3lbeh-2-web.entrypoints=web
      - traefik.http.services.familydashboard-frontend-n3lbeh-2-web.loadbalancer.server.port=80
      - traefik.http.routers.familydashboard-frontend-n3lbeh-2-web.service=familydashboard-frontend-n3lbeh-2-web
      - traefik.enable=true
    networks:
      - dokploy-network
      - default
networks:
  dokploy-network:
    external: true
